### ISSUE TITLE
awilix-koa 1.0.3 doesn't work with awilix 3.0.0-rc.3 - typescript issue

### ISSUE THREAD

**Issue by ith** [jeffijoe/awilix#67]
I'm getting below error trying to compile code. There are some typings missing or I'm using incompatible versions?
```
node_modules/awilix-koa/lib/invokers.d.ts(1,10): error TS2305: Module '"node_modules/awilix/lib/awilix"' has no exported member 'Registration'.
node_modules/awilix-koa/lib/invokers.d.ts(1,24): error TS2305: Module '"node_modules/awilix/lib/awilix"' has no exported member 'RegistrationOptions'.
```

package.json
```
    "awilix": "^3.0.0-rc.3",
    "awilix-koa": "^1.0.3",
    "typescript": "2.6.1"
```

Container configuration
```
import { asFunction, asValue, createContainer } from 'awilix'
import { config } from './config'
import { run } from './some/someController'

export const configureContainer = () => {
    const container = createContainer()

    container.register({
        config: asValue(config),
        someController: asFunction(run),
    })

    return container
}
```

Using container in koa app
```
import { scopePerRequest } from 'awilix-koa'

const container = configureContainer()

app
    .use(scopePerRequest(container))
```

As as side note I had to manually add `"@types/glob": "^5.0.33",` into dev dependencies - it seems awilix is not pulling it as dependency an TS is whining about it.

Please let me know if you need any additional information.

**Comment by jeffijoe** [comment]
Hi! The Registration typing is definitely an issue and will be fixed when v3 is fully released, but most people disable library type checking which I recommend you do as well. `skipLibCheck: true` TypeScript option.

The glob types issue will also resolve itself if you skip library checking. I dont want to ship type dependencies.

**Comment by ith** [comment]
Turned it off and it's working now. Thanks!

If you're planning to fix it with full v3 release than this can stay and wait for release ;)

**Comment by jeffijoe** [comment]
Yes I plan on fixing the `Registration` typing, but I won't include `@types/glob` in `dependencies` 😄

**Comment by jeffijoe** [comment]
Closing as this is now tracked in https://github.com/jeffijoe/awilix-koa/issues/3 😄
